# Change these first
owner: amsterdam # Your GitHub organization or username, where this repository lives
repo: amsterdam-uptime # The name of this repository
user-agent: amsterdam-uptime # Make sure this is unique to avoid conflicts

sites:
  - name: DSO-API
    url: https://api.data.amsterdam.nl/v1/aardgasverbruik/mra_liander/?_format=json
    maxResponseTime: 3000
  - name: Geosearch
    url: https://api.data.amsterdam.nl/geosearch/?datasets=bedrijveninvesteringszones%2Fbedrijveninvesteringszones&lat=52.365804&lon=4.8963802&radius=25
    maxResponseTime: 3000
  - name: Atlas
    url: https://api.data.amsterdam.nl/atlas/search/adres/?format=json&q=Oudeschans+31+X
    maxResponseTime: 3000
  - name: DSO-API Catalog
    url: https://api.data.amsterdam.nl/api/
    maxResponseTime: 3000
  - name: Mapserver
    url: https://map.data.amsterdam.nl/service/?REQUEST=GetMap&FORMAT=image%2Fpng&SRS=EPSG:28992&BBOX=121551.5257836096,488649.3498838544,121704.2287054483,488802.0528056931&VERSION=1.1.0&STYLES=&SERVICE=WMS&WIDTH=256&HEIGHT=256&TRANSPARENT=TRUE&LAYERS=topografie   
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /amsterdam-uptime
  logoUrl: https://api.data.amsterdam.nl/api/gemeente_Amsterdam_logo.svg
  name: Upptime
  introTitle: "Uptime status pagina voor Gemeente Amsterdam APIs"
  thene: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
