# Change these first
owner: amsterdam # Your GitHub organization or username, where this repository lives
repo: amsterdam-uptime # The name of this repository
user-agent: "Amsterdam-uptime"

sites:
  - name: DSO-API
    url: $SITE_URL_DSOAPI
    maxResponseTime: 4000
  - name: DSO-API Catalog
    url: $SITE_URL_CATALOG
    maxResponseTime: 4000    
  - name: API Key Server
    url: $SITE_URL_APIKEYS
    maxResponseTime: 3000
  - name: Amsterdam Schema
    url: $SITE_URL_SCHEMAS
    maxResponseTime: 3000
  - name: BRP Bevragingen
    url: $SITE_URL_BRP_BEVRAGINGEN
    maxResponseTime: 3000
  - name: BRP Kennisgvingen
    url: $SITE_URL_BRP_KENNISGEVINGEN
    maxResponseTime: 3000
  - name: BRP Acc Bevragingen
    url: $SITE_URL_BRP_ACC_BEVRAGINGEN
    maxResponseTime: 3000
  - name: BRP Acc Kennisgvingen
    url: $SITE_URL_BRP_ACC_KENNISGEVINGEN
    maxResponseTime: 3000
  - name: Geosearch
    url: $SITE_URL_GEOSEARCH
    maxResponseTime: 3000
  - name: Atlas Search
    url: $SITE_URL_ATLAS
    headers:
      - "X-Api-Key: $ATLAS_API_KEY"
    maxResponseTime: 3000
  - name: Mapserver
    url: $SITE_URL_MAPSERVER
    maxResponseTime: 3000
  - name: Mapproxy
    url: $SITE_URL_MAPPROXY
    maxResponseTime: 3000
  - name: Panoramas
    url: $SITE_URL_PANORAMAS
    maxResponseTime: 3000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /amsterdam-uptime
  logoUrl: https://api.data.amsterdam.nl/api/gemeente_Amsterdam_logo.svg
  name: Amsterdam Uptime
  introTitle: "Uptime status pagina voor Gemeente Amsterdam APIs"
  thene: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 */2 * * *"
  responseTime: "0 */2 * * *"
  staticSite: "0 */12 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
