# Change these first
owner: amsterdam # Your GitHub organization or username, where this repository lives
repo: amsterdam-uptime # The name of this repository
user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

sites:
  - name: DSO-API
    url: $SITE_URL_DSOAPI
    maxResponseTime: 3000
  - name: Geosearch
    url: $SITE_URL_GEOSEARCH
    maxResponseTime: 3000
  - name: Atlas
    url: $SITE_URL_ATLAS
    maxResponseTime: 3000
  - name: DSO-API Catalog
    url: $SITE_URL_CATALOG
    maxResponseTime: 3000
  - name: Mapserver
    url: $SITE_URL_MAPSERVER
    maxResponseTime: 3000
  - name: DCATD
    url: $SITE_URL_DCATD
    maxResponseTime: 3000
  - name: Panoramas
    url: $SITE_URL_PANORAMAS
    maxResponseTime: 3000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /amsterdam-uptime
  logoUrl: https://api.data.amsterdam.nl/api/gemeente_Amsterdam_logo.svg
  name: Amsterdam Uptime
  introTitle: "Uptime status pagina voor Gemeente Amsterdam APIs"
  thene: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 */2 * * *"
  responseTime: "0 */2 * * *"
  staticSite: "0 */12 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"